---
# tasks file for vscode | EL Family

- name: EL Family | Adding repository {{ vscode_el_repo }}
  yum_repository:
    name: "{{ vscode_el_repo_name }}"
    description: "{{ vscode_el_repo_description }}"
    baseurl: "{{ vscode_el_repo }}"
    gpgcheck: "{{ vscode_el_repo_gpgcheck }}"
    gpgkey: "{{ vscode_el_gpg_key }}"
    enabled: "{{ vscode_el_repo_enabled }}"
    file: "{{ vscode_el_repo_filename }}"
    state: "{{ vscode_repo_desired_state }}"

- name: EL Family | Installing {{ vscode_app_name }}
  yum:
    name: "{{ vscode_app_name }}"
    state: "{{ vscode_desired_state }}"
    update_cache: yes
